export * from './exercise-gender-stats.dto'
export * from './exercise-statistics-dto'
export * from './update-exercise-statistic.dto'
export * from './exercise-category-stats.dto'
export * from './exercise-difficulty-stats.dto'